### ISSUE TITLE
module.js:549, throw err;

### ISSUE THREAD

**Issue by dsubash** [alxshelepenok/gatsby-starter-lumen#387]
$ gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen
module.js:549
    throw err;
    ^

Error: Cannot find module 'entities'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/node_modules/dom-serializer/index.js:5:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by frencojobs** [comment]
This might be an issue relating to gatsby-cli or possible npm, cause the command works perfectly on my machine.  🤷‍♂️
