### ISSUE TITLE
Invalid query in Gatsby-node.js

### ISSUE THREAD

**Issue by bmeverett** [alxshelepenok/gatsby-starter-lumen#61]
After initial clone and running `Gatsby develop` I get an error `Cannot query field "allMarkdownRemark" on type "RootQueryType`

I did get his this warning `warning The gatsby-source-filesystem plugin has generated no Gatsby nodes. Do you need it?` which may be where the error stems from. 

Here is the full stack trace: 
```
gatsby develop
success delete html and css files from previous builds — 0.010 s
success open and validate gatsby-config.js — 0.007 s
success copy gatsby files — 0.038 s
success onPreBootstrap — 0.950 s
warning The gatsby-source-filesystem plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes — 0.120 s
success building schema — 0.168 s
success createLayouts — 0.012 s
⠁ [ { GraphQLError: Cannot query field "allMarkdownRemark" on type "RootQueryType".
    at Object.Field (*/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:65:31)
    at Object.enter (*/node_modules/graphql/language/visitor.js:295:29)
    at Object.enter (*/node_modules/graphql/language/visitor.js:337:25)
    at visit (*/node_modules/graphql/language/visitor.js:227:26)
    at visitUsingRules (*/node_modules/graphql/validation/validate.js:75:22)
    at validate (*/node_modules/graphql/validation/validate.js:60:10)
    at */node_modules/graphql/graphql.js:69:51
    at initializePromise (*/node_modules/es6-promise/dist/es6-promise.js:458:5)
    at new Promise (*/node_modules/es6-promise/dist/es6-promise.js:874:33)
    at graphqlImpl (*/node_modules/graphql/graphql.js:59:10)
    at graphql (*/node_modules/graphql/graphql.js:48:227)
    at graphqlRunner (*/node_modules/gatsby/dist/bootstrap/index.js:368:22)
    at Promise (*/gatsby-node.js:17:5)
    at Promise._execute (*/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (*/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (*/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.exports.createPages (*/gatsby-node.js:11:10)
    at runAPI (*/node_modules/gatsby/dist/utils/api-runner-node.js:110:36)
    at */node_modules/gatsby/dist/utils/api-runner-node.js:187:33
    at */node_modules/async/internal/map.js:27:9
    at replenish (*/node_modules/async/internal/eachOfLimit.js:64:17)
    at iterateeCallback (*/node_modules/async/internal/eachOfLimit.js:49:17)
    message: 'Cannot query field "allMarkdownRemark" on type "RootQueryType".',
    locations: [ [Object] ],
    path: undefined } ]
error gatsby-node.js returned an error
```

**Comment by bmeverett** [comment]
Seems to be because I had a `!` in my folder path where I was running Gatsby from.
